In [3]:
import numpy as np

In [4]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.2]

In [5]:
speed=distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [6]:
np_distance= np.array(distance)
np_time= np.array(time)
speed = np_distance / np_time

In [7]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [8]:
first_numpy_array = np.array([1,2,3,4])

In [9]:
print(first_numpy_array)

[1 2 3 4]


In [10]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
#linespace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [17]:
#one dimensionale array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
TwoD_array = oneD_array.reshape(3,5)
TwoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
ThreeD_array = np.arange(27).reshape(3,3,3)
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [21]:
first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cyclist=np.array(second_trial_cyclist)

In [22]:
np_first_trial_cyclist + np_second_trial_cyclist

array([22, 26, 38, 50])

In [24]:
np_daily_wage = np.array([7,9,13])*15
np_daily_wage

array([105, 135, 195])

In [29]:
cyclist_trials=np.array([np_first_trial_cyclist, np_second_trial_cyclist])
print(cyclist_trials)

[[10 15 17 26]
 [12 11 21 24]]


In [28]:
cyclist_trials = np.array([[10, 15, 17, 26], [12, 11, 21, 24]])
print(cyclist_trials)

[[10 15 17 26]
 [12 11 21 24]]


In [36]:
print(cyclist_trials[0])
print(cyclist_trials[1])
print(cyclist_trials[1][2])
print(cyclist_trials[:, 2]) #columna

[10 15 17 26]
[12 11 21 24]
21
[17 21]


In [37]:
cyclist_trials.shape

(2, 4)

In [38]:
print(cyclist_trials[: , 1:3])

[[15 17]
 [11 21]]


In [69]:
NYC_Borough = np.array(['Manhattan', 'Bronx', 'Brooklyn'])

In [70]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn'], dtype='<U9')

In [71]:
Boroughs_in_NYC = NYC_Borough

In [72]:
NYC_Borough[2] = 'Central Park'
NYC_Borough

array(['Manhattan', 'Bronx', 'Central P'], dtype='<U9')

In [73]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Central P'], dtype='<U9')

In [74]:
NYC_Borough is Boroughs_in_NYC

True

In [77]:
Boroughs_in_NYC[2] = 'Anthony'
print(Boroughs_in_NYC)
print(NYC_Borough)

['Manhattan' 'Bronx' 'Anthony']
['Manhattan' 'Bronx' 'Anthony']


In [79]:
View_of_Borough = Boroughs_in_NYC.view()
print(View_of_Borough)

['Manhattan' 'Bronx' 'Anthony']


In [81]:
View_of_Borough[2] = 'Palermo'
print(Boroughs_in_NYC)
print(NYC_Borough)
print(View_of_Borough)

['Manhattan' 'Bronx' 'Palermo']
['Manhattan' 'Bronx' 'Palermo']
['Manhattan' 'Bronx' 'Palermo']


In [82]:
View_of_Borough is Boroughs_in_NYC

False

In [83]:
Copy_of_Borough = Boroughs_in_NYC.copy()
Copy_of_Borough

array(['Manhattan', 'Bronx', 'Palermo'], dtype='<U9')

In [84]:
Copy_of_Borough[2] = 'Don Bosco'
print(Boroughs_in_NYC)
print(NYC_Borough)
print(View_of_Borough)
print(Copy_of_Borough)

['Manhattan' 'Bronx' 'Palermo']
['Manhattan' 'Bronx' 'Palermo']
['Manhattan' 'Bronx' 'Palermo']
['Manhattan' 'Bronx' 'Don Bosco']


In [85]:
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [86]:
from numpy import pi

In [87]:
np.cos(0)

1.0

In [88]:
np.sin(pi/2)

1.0

In [89]:
np.floor([1.5, 1.6, 2.7, 3.3, 1.1, -0.3, -1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [90]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [92]:
ct = np.array([[10,15,17,26,13,19], [12,11,21,24,14,23]])
ct

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [93]:
ct.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [97]:
ct.reshape(3,4)
ct

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [96]:
ct.resize(2,6)
ct

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [99]:
ct1,ct2=np.hsplit(ct, 2)
print(ct1)
print(ct2)

[[10 15 17]
 [12 11 21]]
[[26 13 19]
 [24 14 23]]


In [101]:
np.hstack((ct1, ct2))

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [102]:
##Trasponer
student_test = np.array([[83,71,57], [54,68,81]])
print(student_test)

[[83 71 57]
 [54 68 81]]


In [103]:
student_test.transpose()

array([[83, 54],
       [71, 68],
       [57, 81]])

In [105]:
#inversa
matriz = np.array([[10,20] , [15,25]])
np.linalg.inv(matriz)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [106]:
# suma de diagonal
np.trace(matriz)

35

In [109]:
np.transpose(np.array([10, 20, 15, 25]))

array([10, 20, 15, 25])