In [1]:
from scipy.integrate import quad

In [5]:
def FunctionToIntegrate(x):
    return x

In [6]:
quad(FunctionToIntegrate, 1 , 2)

(1.5, 1.6653345369377348e-14)

In [7]:
def FunctionToIntegrate2(x,a,b):
    return x*a + b

In [8]:
a=3
b=2

In [9]:
quad(FunctionToIntegrate2, 0,1, args=(a,b))

(3.5, 3.885780586188048e-14)

In [10]:
import scipy.integrate as integrate

In [22]:
def f(x,y) :
    return x + y
integrate.dblquad(f, 0, 1, lambda x: 0, lambda x:2)

(3.0, 4.436070580899685e-14)

In [24]:
import numpy as np
from scipy import optimize

In [25]:
def f(x):
    return x**2 + 5*np.sin(x)

In [26]:
minValue = optimize.minimize(f, x0=2, method='bfgs', options=
                            {'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [28]:
minValue_withoutOutput = optimize.minimize(f, x0=2, method='bfgs')

In [29]:
minValue_withoutOutput

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [31]:
import numpy as np
from scipy.optimize import root

In [32]:
def h(x):
    return x + 3.5 * np.cos(x)

In [34]:
rootValue = root(h, 0.3)

In [35]:
rootValue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [37]:
import numpy as np
from scipy import linalg

In [38]:
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [39]:
type(matrix)

numpy.ndarray

In [40]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [41]:
linalg.det(matrix)

58.0

In [46]:
numArray = np.array([[2,3,1], [-1, 5, 4], [3,2,9]])
numArrayValue = np.array([21,9,6])

In [47]:
linalg.solve(numArray, numArrayValue)

array([ 4.95,  4.35, -1.95])

In [48]:
numSvdArr = np.array([[3,5,1],[9,5,7]])

In [49]:
numSvdArr.shape

(2, 3)

In [50]:
linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [51]:
##Eigenvalues and EigenVectors
import numpy as np
from scipy import linalg

In [52]:
test_rating_data = np.array([[5,8], [7,9]])
eigenValues, eigenVector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenValues

In [53]:
print(first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [54]:
print(eigenVector[:,0])

[-0.81220939  0.58336601]


In [55]:
print(eigenVector[:,1])

[-0.63447346 -0.77294465]


In [56]:
from scipy.stats import norm

In [57]:
##valores random de una distribución normal
norm.rvs(loc=0, scale=1, size=10)

array([ 1.35272806, -1.51000843, -0.37117156,  0.23306419,  0.00704717,
        0.88029861,  0.45114385, -1.84547861,  0.23584219,  1.03687539])

In [59]:
#probabilidad que sea menor que 5
#cumulative distribution function
norm.cdf(5, loc=1, scale=2)

0.9772498680518208

In [60]:
#probability distribution function
norm.pdf(9, loc=0, scale=1)

1.0279773571668917e-18