In [3]:
import numpy as np

In [4]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.2]

In [5]:
speed=distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [6]:
np_distance= np.array(distance)
np_time= np.array(time)
speed = np_distance / np_time

In [7]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [8]:
first_numpy_array = np.array([1,2,3,4])

In [9]:
print(first_numpy_array)

[1 2 3 4]


In [10]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
#linespace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [17]:
#one dimensionale array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
TwoD_array = oneD_array.reshape(3,5)
TwoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
ThreeD_array = np.arange(27).reshape(3,3,3)
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
